#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# Format typescript soruce.
FILES=`git diff-index --cached --name-status $against -- | grep -E '^[AUM].*\.ts$'| cut -c3- | tr '\n' ' '`

if [[ $FILES == '' ]]; then
	exit 0
fi

if npx tsc --noEmit $FILES && npx tsfmt --verify $FILES ; then
	exit 0
fi

echo "some sources in indexed files can't be compiled or are ill-formatted"
exit 1
